# Generated by Django 2.2.2 on 2019-07-24 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('idea', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('problem_statement', models.TextField(max_length=2000)),
                ('executive_summary', models.TextField(max_length=2000)),
                ('objectives', models.TextField(max_length=2000)),
                ('limitations', models.TextField(max_length=2000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Industry_category',
            fields=[
                ('industry_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('industry_category_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Ideas')),
            ],
        ),
        migrations.CreateModel(
            name='Industry_request_category',
            fields=[
                ('industry_request_cat', models.AutoField(primary_key=True, serialize=False)),
                ('industry_request_cat_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('department', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbsSignal',
            fields=[
                ('signal', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Ideas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='OpinionPolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_reply', models.CharField(max_length=200)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Comments')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Ideas')),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.ThumbsSignal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Industry_request',
            fields=[
                ('industry_request', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Industry_category')),
                ('industry_request_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Industry_request_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Industry_committee',
            fields=[
                ('committee', models.AutoField(primary_key=True, serialize=False)),
                ('committee_name', models.CharField(max_length=30)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Comments')),
                ('industry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Industry_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Incubator',
            fields=[
                ('incubator', models.AutoField(primary_key=True, serialize=False)),
                ('incubator_name', models.CharField(max_length=30)),
                ('incubator_description', models.CharField(max_length=120)),
                ('incubator_expertise', models.CharField(max_length=100)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Ideas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Incubatees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Ideas')),
                ('incubator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Incubator')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=120)),
                ('interested_department', models.CharField(max_length=40)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Industry_category')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Ideas'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strathideasapp.Profile'),
        ),
    ]
